### ISSUE TITLE
Trusted publishing: support for Cirrus CI

### ISSUE THREAD

**Issue by abravalheri** [pypi/warehouse#14542]
This is inline with requests such as #13575 and #13888

Cirrus CI supports [OpenID connect tokens](https://cirrus-ci.org/guide/writing-tasks/#internals-of-openid-connect-tokens) (presented to the user via the [`$CIRRUS_OIDC_TOKEN` environment variable](https://cirrus-ci.org/guide/writing-tasks/#environment-variables)) and an user can personalise the audience by setting the [`$CIRRUS_OIDC_TOKEN_AUDIENCE` environment variable](https://cirrus-ci.org/guide/writing-tasks/#environment-variables).

Hopefully this is enough for PyPI to interact with it? Is there anything else that would be necessary?

**Comment by di** [comment]
That's a large part of what's necessary!

The next step would be figuring out which of the ["Cirrus Added Claims"](https://oidc.cirrus-ci.com/.well-known/openid-configuration) would be specific to a given PyPI project (e.g. for GitHub, this is a combination of the owner/repository/workflow claims). At a glance, this would probably be `owner`/`owner_id`, `repository`/`repository_id`, and perhaps `task_name`/`task_id`?

After this, adding the integration to allow PyPI to trust the OIDC token and for PyPI users to configure Cirrus CI as a Trusted publisher would be next steps.

**Comment by abravalheri** [comment]
> At a glance, this would probably be `owner`/`owner_id`, `repository`/`repository_id`, and perhaps `task_name`/`task_id`?

Considering I define something like (untested, just for the sake of brainstorming):

```yaml
# .cirrus.yml
check_task: ...

build_task: ...

test_task: ...

publish_task:
  name: publish (Linux - 3.10)
  container: {image: "python:3.10-bullseye"}
  depends_on: [check, build, test]
  only_if: $CIRRUS_TAG =~ 'v\d.*' && $CIRRUS_USER_PERMISSION == "admin"
  env:
    CIRRUS_OIDC_TOKEN_AUDIENCE: pypi
    TWINE_REPOSITORY: pypi
    TWINE_USERNAME: __token__
  install_script: pip install tox
  prepare_script: <...>
  get_token_script:
    - resp=$(curl -X https://pypi.org/_/oidc/cirrus-ci/mint-token -d "{\"token\": \"${CIRRUS_OIDC_TOKEN}\"}")
    - api_token=$(jq '.token' <<< "${resp}")
    - echo "TWINE_PASSWORD=${api_token}" >> $CIRRUS_ENV
  publish_script:
    - ls dist/*
    - python -m twine upload dist/*

```

I would expect the token to have `platform`, `owner` and `repository` respectively as `github`, `pypi`, `wharehouse` (using this repo as example).
With that, it should be possible to identify the repository/hosting identification. (The `_id` variants are internal to Cirrus and may not be directly translatable to publicly available information).

The `task_name` would be something like `publish`, so it is not unique per-build. If something unique per build is required, `build_id` can give you that...
