### ISSUE TITLE
Project metadata: direct PyPI URL is not considered verified

### ISSUE THREAD

**Issue by woodruffw** [pypi/warehouse#16474]
This is a tiny thing I noticed while testing out @facutuesca's changes: if a project lists its own PyPI URL via `project.urls`, we don't currently consider it verified.

For example, `abi3info`: https://pypi.org/project/abi3info/2024.8.13/

<img width="332" alt="Screenshot 2024-08-13 at 3 12 07 PM" src="https://github.com/user-attachments/assets/e41252d1-0928-4d3b-a505-398e79de5e20">

In this case the `Homepage` is marked as unverified, despite being `https://pypi.org/project/abi3info/`. 

Here's the metadata itself, as it appears in `abi3info`'s `pyproject.toml`:

```toml
[project.urls]
Homepage = "https://pypi.org/project/abi3info/"
Issues = "https://github.com/woodruffw/abi3info/issues"
Source = "https://github.com/woodruffw/abi3info"
Documentation = "https://woodruffw.github.io/abi3info/"
```

## Expected behavior

I think we should consider these "trivially" verified, i.e. if project `$foo` has a URL that equals exactly `https://pypi.org/project/$foo/` (or `https://pypi.org/p/$foo/`), then we should consider that URL verified.

(There might be a minor hiccup around normalizing `$foo` for comparison, since I believe the `/p/` and `/project/` routes are tolerant of non-normalized project names).

CC @facutuesca @di for thoughts 🙂 

xref https://github.com/pypi/warehouse/pull/16205
