### ISSUE TITLE
In Using a Publisher docs, call out that GitHub Actions permissions also need `contents: read` to checkout private repositories

### ISSUE THREAD

**Issue by contrast-jproberts** [pypi/warehouse#17148]
**What's the problem this feature will solve?**
https://docs.pypi.org/trusted-publishers/using-a-publisher/ gives examples of how to change a GitHub Actions workflow to use Trusted Publishing. There's an `IMPORTANT` comment that we add permissions to the job for writing OIDC tokens. I thought these permissions were merged with the default permissions. That's not true though, the permissions must be complete because they will override any defaults.

Users who publish source distributions from a checkout of the GitHub repository, will also need the `contents: read` permission. Without it, the checkout fails with `remote: Repository not found`. For more complete error output, see the bottom code block of https://github.com/orgs/community/discussions/57621 .

**Describe the solution you'd like**
I'd like to see the documentation call out that `contents: read` is also required in the permissions to use `actions/checkout`. I think the practice is common enough that it's worth clarifying. I expect most packages would publish using either a source distribution from `actions/checkout`, or wheels that are either built in the same job from `actions/checkout` or downloaded from a previous job with `actions/download-artifact`. Downloading artifacts doesn't need any extra permissions, but the other two use cases will.

**Comment by di** [comment]
Thanks for filing an issue.

> Users who publish source distributions from a checkout of the GitHub repository, will also need the `content: read` permission. 

I don't think this is exactly true. For example, [here's a workflow](https://github.com/pypa/sampleproject/blob/main/.github/workflows/release.yml) for `sampleproject` that only has a job-level `id-token: write` permission, but it's able to successfully run `actions/checkout` ([example run](https://github.com/pypa/sampleproject/actions/runs/11713038981/job/32625000400)) without additional permissions.

At https://docs.pypi.org/trusted-publishers/using-a-publisher/ , we recommend adding a job-level permission, not a workflow-level permission:

```yaml
jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: pypi
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      # retrieve your distributions here

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
```

The docs at https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token says:

> When you add the permissions key within a specific job, all actions and run commands within that job that use the `GITHUB_TOKEN` gain the access rights you specify. 

My read of this is that job-level permissions are additive to default or specified workflow permissions, which seems to be the case based on that example.

[Here's another example](https://github.com/sigstore/sigstore-python/blob/main/.github/workflows/release.yml) that explicitly sets `contents: read` as a workflow-level permission and then later sets only `id-token: write` as a job-level permission, which also runs  `actions/download-artifact` without any problem ([example run](https://github.com/sigstore/sigstore-python/actions/runs/11520585633/job/32072350152)).

If you have an example workflow & run that is failing when only setting `id-token: wrote` as a **job-level permission**, can you share it here so we can take a closer look?

(PS, note that you have a typo, it's `contents: read`, not `content: read`)

**Comment by contrast-jproberts** [comment]
Thanks for the quick response! You're right about the typo, that was a mistake in the issue but not my code. Sorry about that.

I have been using a job-level permission. I think the issue could be that I'm attempting to checkout a private repository, whereas the examples you've seen are public.

Here's the job contents if it helps. There's a custom action as the second step, but I saw failures in the first.

```
jobs:
  deploy:
    environment: release  # requires approvals for this job to run
    permissions:
      # contents: read # required for cloning the repository # TODO: add this back so actions/checkout doesn't fail.
      id-token: write # required for trusted publishing
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/setup
        with:
          python-version: '3.12'
          build: 'true'
      - name: Deploy to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
```

I can confirm that after I added the `contents: read` permission, everything worked perfectly. I didn't need to make any other changes.

If this is only an issue for private repositories, I understand if that's less prevalent and doesn't meet the bar for a documentation update.
